AllCops:
  TargetRubyVersion: 3
  NewCops: enable

# ——————————————————————————————————————————————————————————————————————————————————————————————————
# Disabled
# ——————————————————————————————————————————————————————————————————————————————————————————————————

Style/MixinUsage:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

# ——————————————————————————————————————————————————————————————————————————————————————————————————
# Configured
# ——————————————————————————————————————————————————————————————————————————————————————————————————

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/Semicolon:
  AllowAsExpressionSeparator: yes

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false # Top-level calls will not be included otherwise.
  AllowedMethods:
    - puts
    - print
    - println
    - raise
    - pp
    - require
    - require_relative
    - require_all
    - require_rel
    - yield
    - exit
    - attr_reader
    - attr_accessor
    - include
    - add_runtime_dependency
    - add_development_dependency
    - gem
    - source

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%r': '[]'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  Width: 4

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
